version: "3.8"

services:
  sourcebox_shortcuts:
    container_name: sourcebox_shortcuts
    image: ghcr.io/sourcebox-be/shortcut:master
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "file://data/db1.sqlite"
      SHORT_URL_DOMAIN: "srcbx.be"
      ORIGIN: "https://shortcode.sourcebox.be"
