version: "3.8"

services:
  sourcebox_shortcuts:
    container_name: sourcebox_shortcuts
    image: sourcebox-shortcuts-dev
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    command: npm run dev --host
    volumes:
      - ./data:/data
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "file://data/db1.sqlite"
      SHORT_URL_DOMAIN: "srcbx.be"
